name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
      options: --user 1001
    env:
      LOGIN: ${{secrets.LOGIN}}
      PASSWORD: ${{secrets.PASSWORD}}
      PROXY_IP: ${{secrets.PROXY_IP}}
      PROXY_LOGIN: ${{secrets.PROXY_LOGIN}}
      PROXY_PASSWORD: ${{secrets.PROXY_PASSWORD}}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30